openapi: 3.0.1
info:
  title: students
  description: API Definition of students
  version: 1.0.0
servers:
- url: http://localhost:8290/info
paths:
  /students:
    get:
      responses:
        default:
          description: Default response
